### PR TITLE
Added Manage Users View and some wireframes

### PR DESCRIPTION
**Pull request by Lyx-22**
Added views and some wireframes

### CODE REVIEW

**Review by cgreen9008 — APPROVED** [review]
Already reviewed this. Looks good to me.

**Review by kabollinger03 — APPROVED** [review]
This looks like a good outline. Any particular concerns or edits can be addressed when we implement web

**Comment by apj11c** [comment]
Please add to a milestone to connect it to ZenHub

**Comment by kabollinger03** [comment]
> 
> 
> Please add to a milestone to connect it to ZenHub

By being in this repo, it is connected to ZenHub. However, connecting it to a story would be good and then adding a milestone to that story and writing it is also good. I linked to story.

**Pull request merged**
